// Original word list for the standard game
export const WORD_LIST = [
  "AFRICA", "AGENT", "AIR", "ALIEN", "ALPS", "AMAZON", "AMBULANCE", "AMERICA",
  "ANGEL", "ANTARCTICA", "APPLE", "ARM", "ATLANTIS", "AUSTRALIA", "AZTEC",
  "BACK", "BALL", "BAND", "BANK", "BAR", "BARK", "BAT", "BATTERY", "BEACH",
  "BEAR", "BEAT", "BED", "BEIJING", "BELL", "BELT", "BERLIN", "BERMUDA",
  "BERRY", "BILL", "BLOCK", "BOARD", "BOLT", "BOMB", "BOND", "BOOM", "BOOT",
  "BOTTLE", "BOW", "BOX", "BRIDGE", "BRUSH", "BUCK", "BUFFALO", "BUG", "BUGLE",
  "BUTTON", "CALF", "CANADA", "CAP", "CAPITAL", "CAR", "CARD", "CARROT",
  "CASINO", "CAST", "CAT", "CELL", "CENTAUR", "CENTER", "CHAIR", "CHANGE",
  "CHARGE", "CHECK", "CHEST", "CHICK", "CHINA", "CHOCOLATE", "CHURCH", "CIRCLE",
  "CLIFF", "CLOAK", "CLUB", "CODE", "COLD", "COMIC", "COMPOUND", "CONCERT",
  "CONDUCTOR", "CONTRACT", "COOK", "COPPER", "COTTON", "COURT", "COVER",
  "CRANE", "CRASH", "CRICKET", "CROSS", "CROW", "CRUSADER", "CRYSTAL", "CUBE",
  "CYCLE", "CZECH", "DANCE", "DATE", "DAY", "DEATH", "DECK", "DEGREE",
  "DIAMOND", "DICE", "DINOSAUR", "DISEASE", "DOCTOR", "DOG", "DRAFT", "DRAGON",
  "DRESS", "DRILL", "DROP", "DUCK", "DWARF", "EAGLE", "EGYPT", "EMBASSY",
  "ENGINE", "ENGLAND", "EUROPE", "EYE", "FACE", "FAIR", "FALL", "FAN", "FENCE",
  "FIELD", "FIGHTER", "FIGURE", "FILE", "FILM", "FIRE", "FISH", "FLUTE", "FLY",
  "FOOT", "FORCE", "FOREST", "FORK", "FRANCE", "GAME", "GAS", "GENIUS",
  "GERMANY", "GHOST", "GIANT", "GLASS", "GLOVE", "GOLD", "GRACE", "GRASS",
  "GREECE", "GREEN", "GROUND", "GROUP", "HAM", "HAND", "HAWK", "HEAD", "HEART",
  "HELICOPTER", "HIMALAYAS", "HOLE", "HOLLYWOOD", "HONEY", "HOOD", "HOOK",
  "HORN", "HORSE", "HORSESHOE", "HOSPITAL", "HOTEL", "ICE", "ICE CREAM", "INDIA",
  "IRON", "IVORY", "JACK", "JAM", "JET", "JUPITER", "KANGAROO", "KETCHUP",
  "KEY", "KID", "KING", "KIWI", "KNIFE", "KNIGHT", "LAB", "LAP", "LASER",
  "LAWYER", "LEAD", "LEMON", "LEPRECHAUN", "LIFE", "LIGHT", "LIMOUSINE", "LINE",
  "LINK", "LION", "LITTER", "LOCH NESS", "LOCK", "LOG", "LONDON", "LUCK",
  "MAIL", "MAMMOTH", "MAPLE", "MARBLE", "MARCH", "MASS", "MATCH", "MERCURY",
  "MEXICO", "MICROSCOPE", "MILLIONAIRE", "MINE", "MINT", "MISSILE", "MODEL",
  "MOLE", "MOON", "MOSCOW", "MOUNT", "MOUSE", "MOUTH", "MUG", "NAIL", "NEEDLE",
  "NET", "NEW YORK", "NIGHT", "NINJA", "NOTE", "NOVEL", "NURSE", "NUT",
  "OCTOPUS", "OIL", "OLIVE", "OLYMPUS", "OPERA", "ORANGE", "ORGAN", "PALM",
  "PAN", "PANTS", "PAPER", "PARACHUTE", "PARK", "PART", "PASS", "PASTE",
  "PENGUIN", "PHOENIX", "PIANO", "PIE", "PILOT", "PIN", "PIPE", "PIRATE",
  "PISTOL", "PIT", "PITCH", "PLANE", "PLASTIC", "PLATE", "PLATYPUS", "PLAY",
  "PLOT", "POINT", "POISON", "POLE", "POLICE", "POOL", "PORT", "POST",
  "POUND", "PRESS", "PRINCESS", "PUMPKIN", "PUPIL", "PYRAMID", "QUEEN",
  "RABBIT", "RACKET", "RAY", "REVOLUTION", "RING", "ROBIN", "ROBOT", "ROCK",
  "ROME", "ROOT", "ROSE", "ROULETTE", "ROUND", "ROW", "RULER", "SADDLE",
  "SALT", "SATELLITE", "SATURN", "SCALE", "SCHOOL", "SCIENTIST", "SCORPION",
  "SCREEN", "SCUBA DIVER", "SEAL", "SERVER", "SHADOW", "SHAKESPEARE", "SHARK",
  "SHIP", "SHOE", "SHOP", "SHOT", "SINK", "SKYSCRAPER", "SLIP", "SLUG", "SMUGGLER",
  "SNOW", "SNOWMAN", "SOCK", "SOLDIER", "SOUL", "SOUND", "SPACE", "SPELL",
  "SPIDER", "SPIKE", "SPINE", "SPOT", "SPRING", "SPY", "SQUARE", "STADIUM",
  "STAFF", "STAR", "STATE", "STICK", "STOCK", "STRAW", "STREAM", "STRIKE",
  "STRING", "SUB", "SUIT", "SUPERHERO", "SWING", "SWITCH", "TABLE", "TABLET",
  "TAG", "TAIL", "TAP", "TEACHER", "TELESCOPE", "TEMPLE", "TEXAS", "THIEF",
  "THUMB", "TICK", "TIE", "TIME", "TOKYO", "TOOTH", "TORCH", "TOWER", "TRACK",
  "TRAIN", "TRIANGLE", "TRIP", "TRUNK", "TUBE", "TURKEY", "UNDERTAKER",
  "UNICORN", "VACUUM", "VAN", "VET", "WAKE", "WALL", "WAR", "WASHER",
  "WASHINGTON", "WATCH", "WATER", "WAVE", "WEB", "WELL", "WHALE", "WHIP",
  "WIND", "WITCH", "WORM", "YARD", "YELLOW", "YOGURT", "YOUTH", "ZEBRA", "ZERO", 
  "ZIGZAG", "ZIPPER", "ZODIAC", "ZONE"
];

// The Simpsons themed word list
export const SIMPSONS_WORD_LIST = [
  "HOMER", "BART", "LISA", "MARGE", "MAGGIE", "SPRINGFIELD", "NUCLEAR", "PLANT",
  "DONUTS", "DUFF", "BEER", "MOE", "TAVERN", "BARNEY", "COMIC", "BOOK", "GUY", 
  "APU", "KWIK", "MART", "KRUSTY", "CLOWN", "ITCHY", "SCRATCHY", "FLANDERS", 
  "NEIGHBOR", "BURNS", "SMITHERS", "RALPH", "WIGGUM", "MILHOUSE", "NELSON", 
  "SKINNER", "CHALMERS", "OTTO", "BUS", "DRIVER", "PATTY", "SELMA", "GRANDPA", 
  "ABE", "TREEHOUSE", "HORROR", "HALLOWEEN", "SIDESHOW", "BOB", "KRABAPPEL", 
  "TEACHER", "TROY", "MCCLURE", "LENNY", "CARL", "PLANT", "WORKER", "CHIEF", 
  "WIGGUM", "POLICE", "DOCTOR", "HIBBERT", "REVEREND", "LOVEJOY", "SNAKE", 
  "JAILBIRD", "MAYOR", "QUIMBY", "DISCO", "STU", "PROFESSOR", "FRINK", "JIMBO", 
  "BULLY", "SQUEAKY", "VOICE", "TEEN", "SAXOPHONE", "BLEEDING", "GUMS", "MURPHY", 
  "KENT", "BROCKMAN", "NEWS", "ANCHOR", "ROD", "TODD", "MAUDE", "DUFFMAN", 
  "MASCOT", "BLINKY", "THREE", "EYES", "FISH", "SANTA", "HELPER", "SNOWBALL", 
  "CAT", "PINCHY", "LOBSTER", "HUGO", "TWIN", "TALLMAN", "EVERGREEN", "TERRACE",
  "KWIK-E-MART", "JUMBO", "ELEPHANT", "MALIBU", "STACY", "DOLL", "STONECUTTERS",
  "SECRET", "CLUB", "MONORAIL", "SHELBYVILLE", "RIVAL", "TOWN", "STEAMED", "HAMS",
  "EMBIGGEN", "CROMULENT", "INANIMATE", "CARBON", "ROD", "DENTAL", "PLAN", "BRACERS"
];

// Marvel themed word list
export const MARVEL_WORD_LIST = [
  "IRON", "MAN", "CAPTAIN", "AMERICA", "SHIELD", "THOR", "HAMMER", "HULK", "SMASH",
  "BLACK", "WIDOW", "HAWKEYE", "ARROW", "NATASHA", "ROMANOFF", "CLINT", "BARTON", 
  "BRUCE", "BANNER", "TONY", "STARK", "STEVE", "ROGERS", "AVENGERS", "ASSEMBLE", 
  "NICK", "FURY", "SHIELD", "AGENT", "COULSON", "MARIA", "HILL", "THANOS", "SNAP", 
  "INFINITY", "STONES", "GAUNTLET", "POWER", "REALITY", "SOUL", "MIND", "SPACE", 
  "TIME", "GUARDIANS", "GALAXY", "STAR", "LORD", "PETER", "QUILL", "GAMORA", "DRAX", 
  "ROCKET", "RACCOON", "GROOT", "MANTIS", "NEBULA", "VISION", "SCARLET", "WITCH", 
  "WANDA", "MAXIMOFF", "QUICKSILVER", "PIETRO", "DOCTOR", "STRANGE", "SORCERER", 
  "SUPREME", "CLOAK", "LEVITATION", "MYSTIC", "ARTS", "BLACK", "PANTHER", "TCHALLA", 
  "WAKANDA", "VIBRANIUM", "SHURI", "OKOYE", "KILLMONGER", "SPIDER", "MAN", "PETER", 
  "PARKER", "WEB", "SLINGER", "CAPTAIN", "MARVEL", "CAROL", "DANVERS", "BINARY", 
  "KREE", "SKRULL", "UNIVERSE", "FALCON", "BUCKY", "WINTER", "SOLDIER", "MULTIVERSE", 
  "MADNESS", "ANT", "WASP", "SCOTT", "LANG", "HANK", "PYM", "PARTICLES", "QUANTUM", 
  "REALM", "HOPE", "VAN", "DYNE", "LOKI", "TRICKSTER", "ASGARD", "ODIN", "HEIMDALL", 
  "BIFROST", "MJOLNIR", "VALKYRIE", "HELA", "SURTUR", "RAGNAROK", "ULTRON", "SOKOVIA", 
  "ACCORDS", "XMEN", "WOLVERINE", "LOGAN", "XAVIER", "MAGNETO", "MYSTIQUE", "JEAN", 
  "GREY", "PHOENIX", "CYCLOPS", "STORM", "PROFESSOR", "DEADPOOL", "WADE", "WILSON", 
  "FANTASTIC", "FOUR", "MISTER", "FANTASTIC", "THING", "INVISIBLE", "WOMAN", "HUMAN", 
  "TORCH", "SILVER", "SURFER", "DOOM", "GALACTUS", "HERALD"
];

// Harry Potter themed word list
export const HARRY_POTTER_WORD_LIST = [
  "HARRY", "POTTER", "WIZARD", "HOGWARTS", "SCHOOL", "MAGIC", "WITCHCRAFT", "WIZARDRY",
  "RON", "WEASLEY", "HERMIONE", "GRANGER", "DUMBLEDORE", "HEADMASTER", "VOLDEMORT",
  "DARK", "LORD", "DEATH", "EATER", "SNAPE", "POTIONS", "MASTER", "MCGONAGALL",
  "TRANSFIGURATION", "HAGRID", "KEEPER", "KEYS", "DOBBY", "HOUSE", "ELF", "MALFOY",
  "SLYTHERIN", "GRYFFINDOR", "HUFFLEPUFF", "RAVENCLAW", "SORTING", "HAT", "QUIDDITCH",
  "BROOM", "NIMBUS", "FIREBOLT", "SEEKER", "GOLDEN", "SNITCH", "BLUDGER", "KEEPER",
  "CHASER", "BEATER", "WAND", "PHOENIX", "FEATHER", "DRAGON", "HEARTSTRING", "UNICORN",
  "HAIR", "DEMENTOR", "AZKABAN", "PRISON", "PATRONUS", "STAG", "OTTER", "TERRIER",
  "CLOAK", "INVISIBILITY", "MARAUDERS", "MAP", "MISCHIEF", "MANAGED", "MOONY", "WORMTAIL",
  "PADFOOT", "PRONGS", "SIRIUS", "BLACK", "REMUS", "LUPIN", "WEREWOLF", "PETTIGREW",
  "RAT", "DIAGON", "ALLEY", "GRINGOTTS", "BANK", "GOBLIN", "OLLIVANDER", "LEAKY",
  "CAULDRON", "BUTTERBEER", "HOGSMEADE", "VILLAGE", "HONEYDUKE", "ZONKOS", "JOKE",
  "SHOP", "HOGWARTS", "EXPRESS", "PLATFORM", "NINE", "THREE", "QUARTERS", "FORBIDDEN",
  "FOREST", "WHOMPING", "WILLOW", "CHAMBER", "SECRETS", "BASILISK", "PARSELTONGUE",
  "SNAKE", "LANGUAGE", "TRIWIZARD", "TOURNAMENT", "GOBLET", "FIRE", "HORCRUX", "SCAR",
  "HUNGARIAN", "HORNTAIL", "DRAGON", "PHILOSOPHER", "STONE", "SORCERER", "DEATHLY",
  "HALLOWS", "ELDER", "WAND", "RESURRECTION", "STONE", "BELLATRIX", "LESTRANGE",
  "NEVILLE", "LONGBOTTOM", "LUNA", "LOVEGOOD", "QUIBBLER", "GINNY", "WEASLEY",
  "BURROW", "ARTHUR", "MOLLY", "FRED", "GEORGE", "PERCY", "BILL", "CHARLIE"
];

// Disney themed word list
export const DISNEY_WORD_LIST = [
  "MICKEY", "MOUSE", "MINNIE", "DONALD", "DUCK", "GOOFY", "PLUTO", "CINDERELLA", 
  "ARIEL", "MERMAID", "BELLE", "BEAST", "CASTLE", "ALADDIN", "JASMINE", "GENIE", 
  "SIMBA", "LION", "KING", "MUFASA", "SCAR", "TIMON", "PUMBAA", "HAKUNA", "MATATA", 
  "WOODY", "BUZZ", "LIGHTYEAR", "TOY", "STORY", "ELSA", "ANNA", "FROZEN", "OLAF", 
  "SNOWMAN", "MOANA", "OCEAN", "MAUI", "DEMIGOD", "HOOK", "RAPUNZEL", "TANGLED", 
  "TOWER", "FLYNN", "RIDER", "PASCAL", "CHAMELEON", "MULAN", "CHINA", "MUSHU", 
  "DRAGON", "BAMBI", "DEER", "FOREST", "THUMPER", "RABBIT", "DUMBO", "ELEPHANT", 
  "FLYING", "PINOCCHIO", "PUPPET", "NOSE", "JIMINY", "CRICKET", "PETER", "PAN", 
  "TINKERBELL", "FAIRY", "NEVERLAND", "HOOK", "CAPTAIN", "WENDY", "POOH", "BEAR", 
  "HONEY", "PIGLET", "TIGGER", "EEYORE", "DONKEY", "HUNDRED", "ACRE", "WOOD", 
  "ALICE", "WONDERLAND", "QUEEN", "HEARTS", "MAD", "HATTER", "CHESHIRE", "CAT", 
  "NEMO", "FINDING", "DORY", "FISH", "MARLIN", "HANK", "OCTOPUS", "STITCH", "LILO", 
  "HAWAII", "EXPERIMENT", "OHANA", "FAMILY", "MERIDA", "BRAVE", "ARCHERY", "ARROW", 
  "TARZAN", "JUNGLE", "JANE", "GORILLAS", "TERK", "POCAHONTAS", "SMITH", "JOHN", 
  "COLORS", "WIND", "MEEKO", "RACCOON", "HERCULES", "MEGARA", "HADES", "OLYMPUS", 
  "GODS", "ZEUS", "MONSTERS", "UNIVERSITY", "SULLY", "MIKE", "WAZOWSKI", "BOO", 
  "RATATOUILLE", "REMY", "RAT", "CHEF", "COOKING", "PARIS", "BAYMAX", "HERO", 
  "HIRO", "TADASHI", "ROBOT", "HEALTHCARE", "ZOOTOPIA", "JUDY", "HOPPS", "NICK", 
  "WILDE", "ENCANTO", "MIRABEL", "MADRIGAL", "BRUNO", "MAGIC", "COLOMBIA", "SOUL", 
  "JOE", "JAZZ", "MUSIC", "PIANO", "COCO", "MIGUEL", "GUITAR", "REMEMBER", "LUCA", 
  "ITALY", "SEA", "MONSTER", "FRIENDSHIP", "TURNING", "RED", "PANDA", "TORONTO"
];

// Video Games themed word list
export const VIDEO_GAMES_WORD_LIST = [
  "MARIO", "LUIGI", "PRINCESS", "PEACH", "BOWSER", "ZELDA", "LINK", "HYRULE", "GANON", "TRIFORCE",
  "MASTER", "SWORD", "MINECRAFT", "CREEPER", "STEVE", "DIAMOND", "CRAFT", "POKÉMON", "PIKACHU", "CHARIZARD",
  "SQUIRTLE", "BULBASAUR", "POKÉ", "BALL", "ASH", "KETCHUM", "PLAYSTATION", "XBOX", "NINTENDO", "SWITCH",
  "CONTROLLER", "CONSOLE", "TETRIS", "BLOCK", "LEVEL", "SONIC", "HEDGEHOG", "TAILS", "KNUCKLES", "SEGA",
  "PACMAN", "GHOST", "PORTAL", "APERTURE", "HALF", "LIFE", "GORDON", "FREEMAN", "VALVE", "STEAM",
  "COUNTER", "STRIKE", "OVERWATCH", "FORTNITE", "BATTLE", "ROYALE", "PUBG", "LEAGUE", "LEGENDS", "DOTA",
  "WARCRAFT", "BLIZZARD", "DIABLO", "HEARTHSTONE", "STARCRAFT", "TERRAN", "PROTOSS", "ZERG", "WITCHER", "GERALT",
  "FINAL", "FANTASY", "CLOUD", "SEPHIROTH", "SQUARE", "ENIX", "METAL", "GEAR", "SOLID", "SNAKE",
  "KOJIMA", "RESIDENT", "EVIL", "UMBRELLA", "ZOMBIE", "CAPCOM", "STREET", "FIGHTER", "RYU", "KEN",
  "MORTAL", "KOMBAT", "SCORPION", "FATALITY", "FINISH", "ASSASSIN", "CREED", "UBISOFT", "EZIO", "DRAKE",
  "UNCHARTED", "NAUGHTY", "DOG", "ELLIE", "JOEL", "LAST", "FALLOUT", "VAULT", "SKYRIM", "ELDER",
  "SCROLLS", "BETHESDA", "DOOM", "QUAKE", "SLAYER", "HALO", "MASTER", "CHIEF", "CORTANA", "BUNGIE",
  "DESTINY", "GUARDIAN", "TRAVELER", "GHOST", "RAID", "DUNGEON", "BOSS", "LOOT", "EXPERIENCE", "POINTS",
  "QUEST", "MISSION", "CAMPAIGN", "PLAYER", "CHARACTER", "AVATAR", "INVENTORY", "WEAPON", "ARMOR", "SHIELD",
  "HEALTH", "MANA", "RESPAWN", "CHECKPOINT", "SAVE", "LOADING", "SCREEN", "GRAPHICS", "RESOLUTION", "FRAME"
];

// Star Wars themed word list
export const STAR_WARS_WORD_LIST = [
  "SKYWALKER", "LUKE", "LEIA", "ORGANA", "VADER", "DARTH", "EMPIRE", "REBEL", "ALLIANCE", "JEDI",
  "SITH", "FORCE", "LIGHT", "DARK", "SIDE", "YODA", "MASTER", "PADAWAN", "APPRENTICE", "LIGHTSABER",
  "CRYSTAL", "KYBER", "DEATH", "STAR", "TATOOINE", "NABOO", "ENDOR", "HOTH", "CORUSCANT", "ALDERAAN",
  "KASHYYYK", "JAKKU", "STARKILLER", "BASE", "REPUBLIC", "SENATE", "CHANCELLOR", "PALPATINE", "EMPEROR", "CLONE",
  "TROOPER", "STORMTROOPER", "DROID", "ASTROMECH", "PROTOCOL", "BATTLE", "BLASTER", "FALCON", "MILLENNIUM", "SOLO",
  "HAN", "CHEWBACCA", "CHEWIE", "WOOKIEE", "KENOBI", "WINDU", "MACE", "DOOKU", "COUNT", "GRIEVOUS",
  "GENERAL", "FEDERATION", "TRADE", "SEPARATIST", "REBEL", "RESISTANCE", "FIRST", "ORDER", "KYLO", "REN",
  "FINN", "REY", "POE", "DAMERON", "DESTROYER", "CRUISER", "BLOCKADE", "RUNNER", "FIGHTER", "WING",
  "SPEEDER", "LANDSPEEDER", "PODRACER", "PODRACING", "SARLACC", "RANCOR", "TAUNTAUN", "DEWBACK", "BANTHA", "HUTT",
  "JABBA", "BOUNTY", "HUNTER", "FETT", "BOBA", "JANGO", "MANDALORIAN", "BESKAR", "ARMOR", "HELMET",
  "MAUL", "SAVAGE", "OPRESS", "AHSOKA", "TANO", "VENTRESS", "ASAJJ", "CODY", "REX", "CLONE",
  "WARS", "GALACTIC", "SPACE", "PLANET", "MOON", "SYSTEM", "SECTOR", "PARSEC", "HYPERSPACE", "JUMP",
  "CANTINA", "MOS", "EISLEY", "SANDCRAWLER", "JAWA", "TUSKEN", "RAIDER", "EWOK", "GUNGAN", "JAR",
  "BINKS", "MIDI", "CHLORIAN", "CARBONITE", "FREEZING", "KAMINO", "GEONOSIS", "MUSTAFAR", "DAGOBAH", "CLOUD",
  "CITY", "BESPIN", "LANDO", "CALRISSIAN", "REBELLION", "IMPERIAL", "TIE", "XWING", "YWING", "AWING"
];

// Types for theme selection
export type WordTheme = 'standard' | 'simpsons' | 'marvel' | 'harry-potter' | 'disney' | 'video-games' | 'star-wars';

// Function to get the word list based on theme
export function getWordList(theme: WordTheme = 'standard'): string[] {
  switch (theme) {
    case 'simpsons':
      return SIMPSONS_WORD_LIST;
    case 'marvel':
      return MARVEL_WORD_LIST;
    case 'harry-potter':
      return HARRY_POTTER_WORD_LIST;
    case 'disney':
      return DISNEY_WORD_LIST;
    case 'video-games':
      return VIDEO_GAMES_WORD_LIST;
    case 'star-wars':
      return STAR_WARS_WORD_LIST;
    case 'standard':
    default:
      return WORD_LIST;
  }
}
